'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Mathematics_Testing_Program.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BINOMIAL1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BINOMIAL1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BINOMIAL1
        '''MULTIPLECHOICE
        '''4
        '''STATISTICS
        '''DISTRIBUTIONS
        '''BINOMIAL
        '''B
        '''5
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property BINOMIAL1_INF() As String
            Get
                Return ResourceManager.GetString("BINOMIAL1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BINOMIAL1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BINOMIAL1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Circle_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Circle_Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUNTEREXAMPLE1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COUNTEREXAMPLE1
        '''FILLINMISSINGLINE
        '''100
        '''PUREMATHS
        '''PROOF
        '''COUNTEREXAMPLE
        '''p1xp2x...xp(n+1)
        '''3
        '''FALSE
        '''FALSE
        '''.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE1_INF() As String
            Get
                Return ResourceManager.GetString("COUNTEREXAMPLE1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUNTEREXAMPLE1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE2_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUNTEREXAMPLE2_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COUNTEREXAMPLE2
        '''FILLINMISSINGLINE
        '''100
        '''PUREMATHS
        '''PROOF
        '''COUNTEREXAMPLE
        '''x^3=p^3/q^3
        '''1
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE2_INF() As String
            Get
                Return ResourceManager.GetString("COUNTEREXAMPLE2_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COUNTEREXAMPLE2_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COUNTEREXAMPLE2_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELASTICIN2D1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ELASTICIN2D1
        '''MULTIPLECHOICE
        '''4
        '''MECHANICS
        '''COLLISIONS
        '''ELASTICIN2D
        '''A
        '''3
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D1_INF() As String
            Get
                Return ResourceManager.GetString("ELASTICIN2D1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELASTICIN2D1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D2_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELASTICIN2D2_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ELASTICIN2D2
        '''MULTIPLECHOICE
        '''4
        '''MECHANICS
        '''COLLISIONS
        '''ELASTICIN2D
        '''B
        '''7
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D2_INF() As String
            Get
                Return ResourceManager.GetString("ELASTICIN2D2_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ELASTICIN2D2_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ELASTICIN2D2_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GRAVITATIONAL1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GRAVITATIONAL1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GRAVITATIONAL1
        '''MULTIPLECHOICE
        '''4
        '''MECHANICS
        '''ENERGY
        '''GRAVITATIONAL
        '''A
        '''3
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property GRAVITATIONAL1_INF() As String
            Get
                Return ResourceManager.GetString("GRAVITATIONAL1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GRAVITATIONAL1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GRAVITATIONAL1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDUCTION01_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDUCTION01_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDUCTION02_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDUCTION02_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INDUCTION1
        '''MULTIPLECHOICE
        '''5
        '''PUREMATHS
        '''PROOF
        '''INDUCTION
        '''C
        '''7
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property INDUCTION1_INF() As String
            Get
                Return ResourceManager.GetString("INDUCTION1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDUCTION1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDUCTION1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INDUCTION2
        '''MULTIPLECHOICE
        '''4
        '''PUREMATHS
        '''PROOF
        '''INDUCTION
        '''C
        '''5
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property INDUCTION2_INF() As String
            Get
                Return ResourceManager.GetString("INDUCTION2_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INDUCTION2_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INDUCTION2_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INTEGRATING_E1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INTEGRATING_E1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INTEGRATING_E1
        '''MULTIPLECHOICE
        '''4
        '''PUREMATHS
        '''INTEGRATION
        '''INTEGRATING#E
        '''B
        '''9
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property INTEGRATING_E1_INF() As String
            Get
                Return ResourceManager.GetString("INTEGRATING_E1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INTEGRATING_E1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INTEGRATING_E1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INTEGRATING_LN1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INTEGRATING_LN1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INTEGRATING_LN1
        '''MULTIPLECHOICE
        '''4
        '''PUREMATHS
        '''INTEGRATION
        '''INTEGRATING#LN
        '''C
        '''4
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property INTEGRATING_LN1_INF() As String
            Get
                Return ResourceManager.GetString("INTEGRATING_LN1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INTEGRATINGLN_1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INTEGRATINGLN_1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KINETIC1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KINETIC1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to KINETIC1
        '''FILLINMISSINGLINE
        '''100
        '''MECHANICS
        '''ENERGY
        '''KINETIC
        '''1/2*85*1.5^2
        '''4
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property KINETIC1_INF() As String
            Get
                Return ResourceManager.GetString("KINETIC1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KINETIC1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KINETIC1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LAWSOFPROBABILITY1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LAWSOFPROBABILITY1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LAWSOFPROBABILITY1
        '''MULTIPLECHOICE
        '''4
        '''STATISTICS
        '''PROBABILITY
        '''LAWSOFPROBABILITY
        '''A
        '''6
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property LAWSOFPROBABILITY1_INF() As String
            Get
                Return ResourceManager.GetString("LAWSOFPROBABILITY1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LAWSOFPROBABILITY1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LAWSOFPROBABILITY1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mathematics_Circle_Neon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mathematics_Circle_Neon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maths_background_main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maths_background_main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NORMAL1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NORMAL1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NORMAL1
        '''MULTIPLECHOICE
        '''4
        '''STATISTICS
        '''DISTRIBUTIONS
        '''NORMAL
        '''A
        '''5
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property NORMAL1_INF() As String
            Get
                Return ResourceManager.GetString("NORMAL1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NORMAL1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NORMAL1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBLIQUE1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBLIQUE1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OBLIQUE1
        '''FILLINMISSINGLINE
        '''100
        '''MECHANICS
        '''COLLISIONS
        '''OBLIQUE
        '''v=u*sqrt(2/3)
        '''9
        '''FALSE
        '''FALSE
        '''.
        '''</summary>
        Friend ReadOnly Property OBLIQUE1_INF() As String
            Get
                Return ResourceManager.GetString("OBLIQUE1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OBLIQUE1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OBLIQUE1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property People() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("People", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_Mark_Neon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_Mark_Neon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_Mark_Neon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_Mark_Neon_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Question_Mark_Neon_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question_Mark_Neon_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Quiz_Sign_Neon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quiz_Sign_Neon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Sign_Neon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Sign_Neon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Symbols() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbols", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VENNDIAGRAMS1_ANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENNDIAGRAMS1_ANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VENNDIAGRAMS1
        '''MULTIPLECHOICE
        '''4
        '''STATISTICS
        '''PROBABILITY
        '''VENNDIAGRAMS
        '''A
        '''2
        '''FALSE
        '''FALSE.
        '''</summary>
        Friend ReadOnly Property VENNDIAGRAMS1_INF() As String
            Get
                Return ResourceManager.GetString("VENNDIAGRAMS1_INF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VENNDIAGRAMS1_QUE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VENNDIAGRAMS1_QUE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property White_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("White_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
